---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: instavote-staging-deploy
  namespace: instavote-staging
spec:
  interval: 1m0s
  path: ./flux
  prune: false
  serviceAccountName: instavote-staging
  targetNamespace: instavote-staging
  sourceRef:
    kind: GitRepository
    name: instavote-staging-deploy

